Hosted improvement
rudderlabs/rudder-server pull request #1029
Opened 2021-05-28 07:32 UTC by Sidddddarth

**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2021-05-28 11:40 UTC, chandumlg approved these changes

2021-06-01 18:26 UTC, psrikanth88 approved these changes

2021-06-02 15:07 UTC, snarkychef requested changes

2021-06-03 07:27 UTC, snarkychef commented on jobsdb/jobsdb.go
> +	config.RegisterIntConfigVariable(1, &maxWriters, false, 1, "JobsDB.maxWriters")
Handled in a separate PR

2021-06-03 07:27 UTC, snarkychef commented on jobsdb/jobsdb.go
> -	//Empty customValFilters means we want to clear for all
Handled in a separate PR

2021-06-03 07:27 UTC, snarkychef commented on jobsdb/jobsdb.go
> +	storeWithRetryChannelBufferLength            int
Handled in a separate PR

2021-06-03 07:28 UTC, snarkychef commented on jobsdb/jobsdb.go
> +	config.RegisterBoolConfigVariable(true, &jd.enableWriterQueue, true, fmt.Sprintf("JobsDB.%v.enableWriterQueue", jd.tablePrefix))
Handled in a separate PR

2021-06-03 07:28 UTC, snarkychef commented on jobsdb/jobsdb.go
> +			panic(fmt.Errorf("unknown read request type: %s", readReq.reqType))
Handled in a separate PR

2021-06-03 07:28 UTC, snarkychef commented on jobsdb/jobsdb.go
> +	jd.markClearEmptyResult(ds, []string{}, []string{}, nil, hasJobs, nil)
Handled in a separate PR

2021-06-03 10:52 UTC, merged