jobsdb_worker_tests
rudderlabs/rudder-server pull request #1062
Opened 2021-06-08 09:21 UTC by Sidddddarth

**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2021-07-01 11:36 UTC, chandumlg approved these changes

2021-07-03 03:01 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +	EventPayload: []byte(`{"receivedAt":"2021-06-06T20:26:39.598+05:30","writeKey":"1rNMpxFxVdoaAdItcXTbVVWdonD","requestIP":"[::1]",  "batch": [{"anonymousId":"anon_id","channel":"android-sdk","context
add a fake write key here?

2021-07-03 03:06 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +			for _, job := range properStoreJobs {
properStoreJobs to mockedStoreJobs?

2021-07-03 03:10 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +	Context("getDSList unit test", func() {
rename it to just the function name without 'unit test'

2021-07-03 03:13 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +			jd.workersAndAuxSetup(ReadWrite, "tt", 0*time.Hour, "", false, QueryFiltersT{})
rename tt to some-prefix

2021-07-03 03:14 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +			jd.workersAndAuxSetup(ReadWrite, "tt", 0*time.Hour, "", false, QueryFiltersT{})
rename tt to some-prefix

2021-07-03 03:15 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +				destinationID := "did1"
rename did1 to some-destination-d

2021-07-03 03:16 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +				customValQuery = " AND ((tt_jobs_1.custom_val='GW'))"
Do we need to hardcode the custom val to 'GW' or can we something like 'some-ds-name'

2021-07-03 03:19 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +			customValQuery := "tt_jobs_1.custom_val='WEBHOOK'"
would it work if we rename WEBHOOK to some-destination-name

2021-07-03 03:23 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +var testJobs = []*JobT{
rename to mockJobs and remove original SourceID's

2021-07-03 03:24 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +var properStoreJobs = []*JobT{
Remove original source-id's and writekeys

2021-07-03 03:25 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +var partiallyProperStoreJobs = []*JobT{
rename this to mockedPartiallyStoredJobs

2021-07-03 03:29 UTC, cisse21 requested changes

2021-07-03 03:29 UTC, cisse21 commented on jobsdb/jobsdb_test.go
> +			err.Code = "22P02"
Comment indicating what the error code is

2021-07-05 06:44 UTC, cisse21 approved these changes

2021-07-05 06:45 UTC, merged