added for custom sources
rudderlabs/rudder-server pull request #1134
Opened 2021-07-22 07:17 UTC by ruchiramoitra

**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2021-07-22 09:58 UTC, arnab-p reviewed
LGTM

2021-07-22 09:58 UTC, arnab-p approved these changes

2021-07-27 13:10 UTC, psrikanth88 requested changes

2021-07-27 13:10 UTC, psrikanth88 commented on gateway/webhook/webhook.go
> +	if err := r.ParseForm(); err != nil {
should we check the content type header for form data and then only parse for form data etc

2021-07-27 13:10 UTC, psrikanth88 commented on gateway/webhook/webhook.go
> +		jsonByte, err = json.Marshal(multipartForm)
since we are giving higher pref for multipart form, can we check for multipart form first and skip parseForm if multipart form data is there

2021-07-28 06:17 UTC, psrikanth88 requested changes

2021-07-28 06:17 UTC, psrikanth88 commented on gateway/webhook/webhook.go
> +		r.Header.Set("Content-Type", "[application/json]")
do we need the [ brackers around the content-type?

2021-07-28 06:17 UTC, psrikanth88 commented on gateway/webhook/webhook.go
> +	if contentType == "application/x-www-form-urlencoded" {
do we need to do a case insensitive comparison or does the http package return it in lowercase irrespective of what the user set

2021-07-28 06:17 UTC, psrikanth88 commented on gateway/webhook/webhook.go
> +		r, err = http.NewRequest("POST", r.URL.String(), bytes.NewBuffer(jsonByte))
we might lose headers like x-forwarded-for that contain the request IP address etc when we create a new request. Should we edit the existing request or copy over the headers to new one

2021-07-28 06:17 UTC, psrikanth88 commented on gateway/webhook/webhook.go
> +			http.Error(w, "Could not parse form", 400)
can we use the `failRequest` to return error here too? Also increment the metrics count etc like above ```webhook.failRequest(w, r, response.GetStatus(response.NoWriteKeyInQueryParams), response.GetStatusCode(response.NoWriteKeyInQueryParams), "noWriteKey")
atomic.AddUint64(&webhook.ackCount, 1)```

2021-07-28 07:52 UTC, psrikanth88 approved these changes

2021-08-05 10:44 UTC, merged