wh: batch staging files
rudderlabs/rudder-server pull request #1214
Opened 2021-08-31 11:31 UTC by dhawal1248

**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2021-09-03 12:27 UTC, psrikanth88 requested changes

2021-09-03 12:27 UTC, psrikanth88 commented on warehouse/warehouse.go
> +		if !batchStagingFiles {
and also delete any load files that are there. Since the later deletion is by upload_id and these will not have upload_id

2021-09-09 06:41 UTC, sivashanmukh requested changes

2021-09-21 14:54 UTC, dhawal1248 commented on warehouse/warehouse.go
> +		if !batchStagingFiles {
When we set the uploadJob to waiting and it gets picked up -  the uploadId remains the same,right?
When the upload runs, all previous load files for the uploadId will be deleted.
Am i missing something here? 
@psrikanth88

2021-09-21 20:31 UTC, dhawal1248 commented on warehouse/upload.go
> +	batchedStagingFiles := []StagingFileBatchT{}
Will discuss with you regd this @psrikanth88

2022-04-15 02:21 UTC, closed without merging