added batch deleter test
rudderlabs/rudder-server pull request #1563
Opened 2022-01-11 08:40 UTC by saurav-malani

**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2022-01-18 05:19 UTC, lvrach requested changes
Overall implementation is good, requesting changes for error handling

2022-01-18 05:19 UTC, lvrach commented on regulation-worker/internal/delete/batch/batch_test.go
> +				goldenFilePtr, err := os.OpenFile(goldenFilesList[i], os.O_RDWR, 0644)
Any reason for using `OpenFile` ? We can simplify things by:
```suggestion
				goldenFilePtr, err := os.Open(goldenFilesList[i])
```

2022-01-18 05:19 UTC, lvrach commented on regulation-worker/internal/delete/batch/batch_test.go
> +					panic(err)
Prefer:
```suggestion
					t.Fatal(err)
```

or

```suggestion
     require.NoError(err)
```

2022-01-18 05:19 UTC, lvrach commented on regulation-worker/internal/delete/batch/batch_test.go
> +	_, err = exec.Command("cp", "-r", "./mockBucket", tmpDirPath).Output()
A good idea would be to move this to a constant ?

2022-01-18 05:19 UTC, lvrach commented on regulation-worker/internal/delete/batch/batch_test.go
> +		fmt.Println("error: ", err, " while opening file: ", fileName)
Why not returning an error ? The following command will fail for sure

2022-01-18 05:19 UTC, lvrach commented on regulation-worker/internal/delete/batch/batch_test.go
> +		return nil
Again error could be propagated.

2022-01-24 08:13 UTC, chandumlg approved these changes

2022-01-24 11:04 UTC, lvrach approved these changes

2022-01-24 11:07 UTC, merged