Temporary PR for initial Review : : Integration test refactor
rudderlabs/rudder-server pull request #1599
Opened 2022-01-26 11:27 UTC by rspriyamdixit

**Fixes** # (*issue*)
Temporary PR for initial Review :
1. Code restructure 
2. .env file for integration test
## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2022-01-26 17:06 UTC, lvrach requested changes
Please avoid the usage of global variables, like:
```
var (
	pool             *dockertest.Pool
	err              error
	network          *dc.Network
	brokerPort       string
	localhostPort    string
	localhostPortInt int
)
```

in favor of returning concreate structs.

2022-02-01 16:00 UTC, lvrach requested changes
The usage of global variables is not resolved. I've left an example on how can be done for Kafka. It should be hard to apply this in other destinations as well.

2022-02-02 06:28 UTC, lvrach commented on testhelper/destination/rudderserver.go
> +func SetJobsDB(Test *Test) (*sql.DB, *dockertest.Resource) {
Even if we currently only use sql.DB, is better to return the whole `type ServerTest struct`. Making the `db` exportable `DB`. 

This way if we need to return something extra like:
* database name
* username
* password
* port

We can easily add them.

I would suggest even now to return DB_DSN in form of `url.URL`

2022-02-02 06:28 UTC, lvrach commented on testhelper/destination/kafka.go
> +func SetKafka(Test *Test, z *dockertest.Resource) *dockertest.Resource {
this can remain unexported
```suggestion
func setKafka(Test *Test, z *dockertest.Resource) *dockertest.Resource {
```

2022-02-09 19:04 UTC, lvrach approved these changes

2022-02-10 04:33 UTC, chandumlg approved these changes

2022-02-10 04:33 UTC, merged