feature(BQStream): add support for batch of properties
rudderlabs/rudder-server pull request #2367
Opened 2022-08-29 17:50 UTC by akashrpo

# Description

> add support to accept array of properties

## Notion Ticket

https://www.notion.so/rudderstacks/bqstream-Add-batching-support-8f9470b6eaac4fc1a2d750bc6827ded0

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2022-08-30 00:36 UTC, sanpj2292 commented
@akashrpo 
Basically, we will need to do two things 
- Move BQStream to routerTransform
- There will always be batching by default
- If not, if there is a single event -> this change will break I think(cause error response). So we will need to tread this way carefully

cc: @utsabc @koladilip

2022-08-30 03:37 UTC, koladilip requested changes

2022-08-30 03:45 UTC, sanpj2292 commented on services/streammanager/bqstream/bqstreammanager.go
>  	props := parsedJSON.Get("properties").String()
Are you saying we will have to send `properties` in the form of an array(from transformer) ?

2022-08-30 04:46 UTC, koladilip commented on services/streammanager/bqstream/bqstreammanager.go
>  	props := parsedJSON.Get("properties").String()
No, I am suggesting to handle both cases in server only even if you get array or single element
https://pkg.go.dev/github.com/tidwall/gjson#Result.Array - This returns array always. or use:
https://pkg.go.dev/github.com/tidwall/gjson#Result.IsArray and build logic based on it.

2022-08-30 05:00 UTC, sanpj2292 commented on services/streammanager/bqstream/bqstreammanager.go
>  	props := parsedJSON.Get("properties").String()
Got it

2022-10-10 17:52 UTC, akashrpo commented on services/streammanager/bqstream/bqstreammanager.go
>  	props := parsedJSON.Get("properties").String()
Built the logic around https://pkg.go.dev/github.com/tidwall/gjson#Result.IsArray

2022-10-12 09:05 UTC, koladilip approved these changes

2022-10-12 10:03 UTC, sanpj2292 approved these changes

2022-10-12 16:12 UTC, utsabc approved these changes

2022-10-12 16:16 UTC, koladilip commented
@akashrpo Please add tests for Produce then we can merge.

2022-10-14 05:45 UTC, koladilip commented
@akashrpo if all checks are passed you can merge

2022-10-14 06:01 UTC, koladilip approved these changes

2022-10-14 06:24 UTC, merged