feat: regulation worker support for parallel processing
rudderlabs/rudder-server pull request #2825
Opened 2022-12-20 07:39 UTC by atzoum

# Description

A single regulation worker instance can now process multiple jobs in parallel

## Notion Ticket

[Link](https://www.notion.so/rudderstacks/8aac9087df644365acdf64e28e290153?v=6e06b0a5ade24f0aa5ffe05dc2972e84&p=e9365dded761444b996aa1e79f2cc80e&pm=s)

## Security

- [x] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2022-12-21 10:19 UTC, saurav-malani requested changes
We missed to handle the case where two workers/goroutines are trying to delete from same batch deleter (s3 bucket) in that case the same meta file (`rudderDeleteTracker.txt`) that we maintain in s3 would be used by both the workers, which will create problem. 
A simple solution would be to rename the status tracker file with goroutine & worker name (horizontally scaling case).

2022-12-21 10:28 UTC, atzoum commented on regulation-worker/internal/service/looper.go
> +	workers := config.GetInt("NUM_WORKERS", 5)
1 worker == 1 goroutine

2022-12-21 10:29 UTC, atzoum commented on regulation-worker/internal/service/looper.go
> +	b := make(chan *model.Job, 1)
To be frank, I don't even think we really need a buffered channel after all

2022-12-21 10:31 UTC, atzoum commented
> We missed to handle the case where two workers/goroutines are trying to delete from same batch deleter (s3 bucket) in that case the same meta file (`rudderDeleteTracker.txt`) that we maintain in s3 would be used by both the workers, which will create problem. A simple solution would be to rename the status tracker file with goroutine & worker name (horizontally scaling case).

Thanks for pointing that out, I will have a look.

@achettyiitr is there any other potential issue that you can find with running parallel deletions for `S3` or `S3_DATALAKE`?

2022-12-21 10:33 UTC, achettyiitr commented
> > We missed to handle the case where two workers/goroutines are trying to delete from same batch deleter (s3 bucket) in that case the same meta file (`rudderDeleteTracker.txt`) that we maintain in s3 would be used by both the workers, which will create problem. A simple solution would be to rename the status tracker file with goroutine & worker name (horizontally scaling case).
> 
> Thanks for pointing that out, I will have a look.
> 
> @achettyiitr is there any other potential issue that you can find with running parallel deletions for `S3` or `S3_DATALAKE`?

cc @abhimanyubabbar

2022-12-21 12:11 UTC, atzoum commented
> > > We missed to handle the case where two workers/goroutines are trying to delete from same batch deleter (s3 bucket) in that case the same meta file (`rudderDeleteTracker.txt`) that we maintain in s3 would be used by both the workers, which will create problem. A simple solution would be to rename the status tracker file with goroutine & worker name (horizontally scaling case).
> > 
> > 
> > Thanks for pointing that out, I will have a look.
> > @achettyiitr is there any other potential issue that you can find with running parallel deletions for `S3` or `S3_DATALAKE`?
> 
> cc @abhimanyubabbar

Can we do without a `rudderDeleteTracker.txt`? Why is it important?

2022-12-21 12:19 UTC, abhimanyubabbar commented
> > > > We missed to handle the case where two workers/goroutines are trying to delete from same batch deleter (s3 bucket) in that case the same meta file (`rudderDeleteTracker.txt`) that we maintain in s3 would be used by both the workers, which will create problem. A simple solution would be to rename the status tracker file with goroutine & worker name (horizontally scaling case).
> > > 
> > > 
> > > Thanks for pointing that out, I will have a look.
> > > @achettyiitr is there any other potential issue that you can find with running parallel deletions for `S3` or `S3_DATALAKE`?
> > 
> > 
> > cc @abhimanyubabbar
> 
> Can we do without a `rudderDeleteTracker.txt`? Why is it important?

The rudderDeleteTracker file captures the `fileId's` that are already cleaned and can be skipped the next time the tracker starts again after temporarily erroring out.

2023-01-02 11:25 UTC, saurav-malani commented
Another scenario that we need to take care of:-

<img width="191" alt="Screenshot 2023-01-02 at 4 52 50 PM" src="https://user-images.githubusercontent.com/17248908/210224807-44fd25b2-59f2-4529-a774-4112d50dce52.png">

As here two worker/go routine subsequently downloaded the same file. Hence, the cleanup done by `W1` would be overwritten by `W2`.

2023-01-31 02:10 UTC, closed without merging