fix: RoleBasedAuth parameter wasn't being set correctly
rudderlabs/rudder-server pull request #3134
Opened 2023-03-28 14:13 UTC by raman2805

# Description

Setting the sessionConfig.RoleConfigAuth parameter before throwing an error for incompatible configs

2023-03-28 14:21 UTC, koladilip requested changes

2023-03-28 14:21 UTC, koladilip commented on utils/awsutils/session.go
> +	}
```suggestion
	if  sessionConfig.IAMRoleARN == "" {
		sessionConfig.RoleBasedAuth = false
	}
```

2023-03-29 04:14 UTC, koladilip approved these changes

2023-04-03 07:57 UTC, achettyiitr approved these changes

2023-04-03 07:57 UTC, merged