fix: respect user schema modification by user in warehouse
rudderlabs/rudder-server pull request #3419
Opened 2023-05-30 10:11 UTC by saurav-malani

# Description
PR to make sure that the changes done by customer in user schema in warehouse is incorporated in `consolidatedSchema`

## Notion Ticket

https://www.notion.so/rudderstacks/Users-and-Identifies-table-schema-difference-103c3ee744194c9984be4c497527cf74?pvs=4

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2023-05-30 12:19 UTC, achettyiitr commented on warehouse/schema.go
> +	}
```suggestion
	for colName, colType := range warehouseSchema[usersTable] {
		if _, ok := consolidatedSchema[identifiesTable][colName]; !ok {
			consolidatedSchema[identifiesTable][colName] = colType
		}
	}
```

2023-06-01 05:15 UTC, saurav-malani commented on warehouse/schema.go
> +	}
Oops, thanks for pointing it out. 😄

2023-06-01 05:50 UTC, lvrach requested changes

2023-06-01 05:50 UTC, lvrach commented on warehouse/schema.go
> +	fmt.Println("consolidatedSchema before override: ", consolidatedSchema[identifiesTable])
```suggestion
```

2023-06-01 05:50 UTC, lvrach commented on warehouse/schema.go
> +	fmt.Println("consolidatedSchema after override: ", consolidatedSchema[identifiesTable])
```suggestion
```

2023-06-01 06:17 UTC, achettyiitr approved these changes

2023-06-01 07:45 UTC, saurav-malani commented on warehouse/schema.go
> +	fmt.Println("consolidatedSchema before override: ", consolidatedSchema[identifiesTable])
sorry, removed.

2023-06-06 07:47 UTC, lvrach approved these changes

2023-06-06 08:22 UTC, merged