[WIP] feat: report failed messages in processor, router and batchrouter
rudderlabs/rudder-server pull request #3914
Opened 2023-09-26 15:28 UTC by atzoum

# Description

< Replace with adequate description for this PR as per [Pull Request document](https://www.notion.so/rudderstacks/Pull-Requests-40a4c6bd7a5e4387ba9029bab297c9e3) >

## Linear Ticket

< Replace with Linear Link >

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2023-10-12 08:23 UTC, achettyiitr requested changes

2023-10-12 08:23 UTC, achettyiitr commented on testhelper/backendconfigtest/destination_builder.go
> +// WithDestinationTransformation adds a config option to the destination definition
```suggestion
// WithDefinitionConfigOption adds a config option to the destination definition
```

2023-10-12 08:23 UTC, achettyiitr commented on testhelper/transformertest/handler_funcs.go
> +// ValidationErrorTransformerHandler mirrors the request payload in the response but uses an error status code along with the provided validation errors
```suggestion
// ViolationErrorTransformerHandler mirrors the request payload in the response but uses an error status code along with the provided validation errors
```

2023-10-12 13:46 UTC, achettyiitr approved these changes

2023-10-13 06:56 UTC, lvrach approved these changes

2023-10-13 06:56 UTC, lvrach commented on integration_test/reporting_dropped_events/reporting_dropped_events_test.go
> +			_ = wg.Wait()
```suggestion
			require.NoError(t, wg.Wait())
```

2023-10-13 06:57 UTC, merged