fix: add wait for get supported destinations in regulation worker
rudderlabs/rudder-server pull request #4311
Opened 2024-01-12 13:30 UTC by koladilip

# Description

We need to wait for the transformer features so that the regulation worker behaves as expected with jobs

## Linear Ticket
https://linear.app/rudderstack/issue/INT-1336/add-support-for-regulation-in-featuresjson

Resolves INT-1336

## Security

- [x] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2024-01-12 13:32 UTC, cisse21 approved these changes

2024-01-12 14:02 UTC, chandumlg approved these changes

2024-01-12 14:02 UTC, chandumlg requested changes
Tests failed!

2024-01-13 05:49 UTC, chandumlg approved these changes

2024-01-13 06:03 UTC, merged