Gv/rudderId
rudderlabs/rudder-server pull request #496
Opened 2020-08-18 09:35 UTC by gane5hvarma

Introducing rudderId in events

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2020-08-19 09:27 UTC, psrikanth88 approved these changes

2020-08-19 10:04 UTC, SumanthPuram requested changes
We need to change the function to GetRudderID. 

```
func GetAnonymousID(event types.SingularEventT) (string, bool) {
```

2020-08-19 10:44 UTC, gane5hvarma commented
@SumanthPuram this is being used to fetch anonymous id and user id in few places. should we add getAnonymousId and getRudderId functions

2020-08-24 08:33 UTC, SumanthPuram commented on processor/transformer/transformer.go
> +					prevUserID, ok := misc.GetRudderID(clientEvents[inputIdx-1].Message)
Change the variable names to prevRudderID and currentRudderID?

2020-08-24 12:44 UTC, SumanthPuram approved these changes

2020-08-24 22:57 UTC, SumanthPuram approved these changes

2020-10-08 09:44 UTC, chandumlg approved these changes

2020-10-22 08:07 UTC, merged