chore: drop upload id from wh_schema
rudderlabs/rudder-server pull request #5336
Opened 2024-12-04 12:28 UTC by cisse21

# Description
Removes unused wh_upload_id from wh_schema table

## Linear Ticket

Fixes WAR-102

## Security

- [ ] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2024-12-04 12:31 UTC, achettyiitr approved these changes

2024-12-05 07:37 UTC, achettyiitr approved these changes

2024-12-05 08:19 UTC, ktgowtham requested changes

2024-12-05 08:19 UTC, ktgowtham commented on sql/migrations/warehouse/000026_drop_wh_upload_id_column.up.sql
> +ALTER TABLE wh_schemas DROP COLUMN IF EXISTS wh_upload_id;
Let's make this nullable in this release. If we revert image, not having this column will create problems. 
In the next release we can drop the column. We can capture a task in linear to not miss this.

2024-12-05 11:47 UTC, ktgowtham approved these changes

2024-12-06 03:02 UTC, merged