chore: add error msg in the logs when gw req fails
rudderlabs/rudder-server pull request #5369
Opened 2024-12-11 10:17 UTC by mihir20

# Description

add error msg in the logs when gw req fails

## Linear Ticket

< Replace with Linear Link ( [create](https://linear.new?title=Awesome-pr-without-linear-ticket) or [search](https://linear.app/rudderstack/search) linear ticket) or  >

## Security

- [x] The code changed/added as part of this pull request won't create any security issues with how the software is being used.

2024-12-11 10:35 UTC, BonapartePC approved these changes

2024-12-11 10:35 UTC, BonapartePC commented on gateway/handle.go
>  			goto requestError
All the errors going to `requestError` should be printing error message. Examples: Line 664 and 680

2024-12-11 10:35 UTC, BonapartePC commented on gateway/handle.go
> -		gw.logger.Infon("response",
Let's also log properties if they are available after unmarshalling

2024-12-12 08:40 UTC, lvrach commented on gateway/handle.go
> +		return nil, response.InvalidJSON, fmt.Errorf("unmarshalling request body: %w", err)
This is not an elegant way to do this. Using wrapping and using `if errors.As(err, &e)` to extract response error would be a better approach. https://go.dev/blog/go1.13-errors

If this is too complex given the time constrains, I will log the error here.

2024-12-12 12:50 UTC, fracasula requested changes

2024-12-12 12:53 UTC, fracasula commented on gateway/handle.go
> +		gw.logger.Errorn("no messages in request", logger.NewStringField("body", string(body)))
Again, let's not dump the body. Payloads should be encrypted and uploaded somewhere safe, not logged like this.

2024-12-12 12:53 UTC, fracasula commented on gateway/handle.go
> +		gw.logger.Errorn("no messages in request", logger.NewStringField("body", string(body)))
Same applies to all other places where the message payload is being dumped.

2024-12-12 16:37 UTC, fracasula commented on gateway/handle.go
> +		gw.logger.Errorn("no messages in request", logger.NewStringField("body", string(body)))
Uploading should be encrypted imo.

2024-12-16 14:00 UTC, fracasula approved these changes

2024-12-18 12:42 UTC, merged