Module level logging1
rudderlabs/rudder-server pull request #620
Opened 2020-10-29 11:48 UTC by Amol-Thakur

**Fixes** # (*issue*)

## Type of change
- [ ] New feature (non-breaking change which adds functionality)
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2020-10-30 07:03 UTC, snarkychef requested changes
Use pkgLogger for logging in gateway, processor, jobsdb instead of logger package functions.

2020-11-02 12:00 UTC, snarkychef requested changes
Let's also remove static functions in logger package for Infof etc. as they should not be needed anymore.

2020-11-02 14:31 UTC, snarkychef requested changes

2020-11-02 14:31 UTC, snarkychef commented on services/streammanager/kinesis/kinesismanager.go
> +	pkgLogger = logger.NewLogger().Child("streammanager").Child("kinesismanager")
streammanager.kinesis

2020-11-02 16:39 UTC, snarkychef approved these changes

2020-11-03 07:17 UTC, SumanthPuram approved these changes

2020-11-03 07:28 UTC, chandumlg approved these changes

2020-11-03 11:56 UTC, merged