WH: Verify event counts in load file gen and export stages
rudderlabs/rudder-server pull request #802
Opened 2021-01-29 00:10 UTC by psrikanth88

**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2021-02-01 12:04 UTC, sivashanmukh requested changes

2021-02-01 12:04 UTC, sivashanmukh commented on warehouse/upload.go
> +		warehouseutils.WarehouseLoadFilesTable, startID, endID, job.warehouse.Source.ID, job.warehouse.Destination.ID)
Merge these two funcs

2021-02-01 12:06 UTC, sivashanmukh commented on warehouse/upload.go
> +		job.counterStat("warehouse_staging_load_file_events_count_mismatched").Increment()
Instead gauge the difference

2021-02-01 12:07 UTC, sivashanmukh commented on warehouse/upload.go
> +		job.counterStat(`post_load_table_rows`, tag{name: "tableName", value: strings.ToLower(tName)}).Count(int(totalAfterLoad))
Lets use Gauge here as well

2021-02-01 12:08 UTC, sivashanmukh requested changes
Guage metrics

2021-02-02 00:01 UTC, psrikanth88 commented on warehouse/table_upload.go
> +	sqlStatement := fmt.Sprintf(`SELECT total_events FROM %s WHERE wh_upload_id=%v AND table_name='%s'`, warehouseutils.WarehouseTableUploadsTable, tableUpload.uploadID, tableUpload.tableName)
done

2021-02-02 12:10 UTC, sivashanmukh approved these changes
LGTM

2021-02-02 12:13 UTC, sivashanmukh commented on warehouse/bigquery/bigquery.go
> +	it, err := bq.Db.Query(sqlStatement).Read(bq.BQContext)
Handle this error

2021-02-02 12:14 UTC, sivashanmukh commented on warehouse/upload.go
> +	var locations []string
Merge this with the next line?

2021-02-02 12:17 UTC, sivashanmukh requested changes

2021-02-02 12:17 UTC, sivashanmukh commented on warehouse/bigquery/bigquery.go
> +	it, err := bq.Db.Query(sqlStatement).Read(bq.BQContext)
Handle this error

2021-02-02 12:23 UTC, sivashanmukh approved these changes
LGTM

2021-02-04 10:06 UTC, SumanthPuram approved these changes

2021-02-04 14:14 UTC, merged