id res bq
rudderlabs/rudder-server pull request #885
Opened 2021-03-18 13:11 UTC by gane5hvarma

**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

2021-04-01 08:06 UTC, psrikanth88 requested changes
@gane5hvarma Also while creating view for identity mappings table we should partition by merge_property_type + merge_property_value and return the latest rudderId for the combination. Deduping on id in view will not be useful

2021-04-01 08:06 UTC, psrikanth88 commented on warehouse/bigquery/bigquery.go
> +	identityMappingsTable := warehouseutils.IdentityMappingsWarehouseTableName(PROVIDER)
merge both LoadIdentityMergeRulesTable and LoadIdentityMappingsTable into one func. Or maybe reuse the loadTable func as we are not doing anything different with dedup right?

2021-04-20 09:09 UTC, psrikanth88 approved these changes

2021-04-21 06:12 UTC, sivashanmukh approved these changes
LGTM

2021-04-26 13:06 UTC, sivashanmukh approved these changes
LGTM

2021-04-26 13:07 UTC, merged